### ISSUE TITLE
Calculate minima step (n_snps_bw_bpoints)

### ISSUE THREAD

**Issue by Sohambiswas8** [jmacdon/LDblocks_GRCh38#5]
Hi, 

Thank you for your previous suggestions and I could replicate the steps in LDetect till covariance matrix and subsequent vectors. I am using our in-house genotype data, and the results have been satisfactory according to our data, as I am evaluating each step and hence it took a while to get back to you again. 

As you rightly mentioned in the "calculate minima" step there seems to be a bug and I tried to comment out the lines you pointed. Yet, I am getting an error which seems there is an issue with 'n_snps_bw_bpoints'. I once again ran all the previous steps now with 1KG EUR data as you have done and again in step 4, I encountered the same error. I used 50 as the Number of SNPs Between Breakpoints as mentioned in LDetect. 

But I noticed, in your script, you set the value of 'n_snps_bw_bpoints' to 2nd  argument passed to the script and in the README you mentioned only one argument: `qsub ./runStep4.sh EUR` i.e. only `$pop `argument. Where is the `$nsnps` argument used I couldn't understand. So I was also unable to find the value that you used or at least, how you got that value. 
It will be really helpful if you once again look into the matter. Previously with your suggestions, I was able to go forward with the steps. 

Thanks,
Soham

**Comment by Sohambiswas8** [comment]
Hi, 

I once again read your paper (https://doi.org/10.1101/2022.03.04.483057) and it looks like `n_snps_bw_bpoints` is the same average no. of SNPs per block, that was used to partition each chromosome in the P00_00_partition_chromosome.py file. In that case, it is the default 5000, that I used (for chromosome 22, it resulted in 20 blocks). However, I am still confused as the README file of LDetect shows a different value. Commenting out the lines in P02_minima_pipeline.py also doesn't help. I am getting the same error. I am attaching the error in a separate file (a KeyError: 'hanning' during search for filter width). 
[error_minima.log](https://github.com/user-attachments/files/15971416/error_minima.log)

Since you have tested LDetect and published the data, which seems quite reproducible, it would be helpful if you could suggest how to fix this issue. I really want to compute the LD blocks.

**Comment by jmacdon** [comment]
I believe you have mis-read the paper. It says

We set the average block size to 7,000 SNPs to obtain comparable block sizes to the previously derived GRCh37 blocks

As for the error you get, we didn't see that one, so I am not sure I can help you. I spent many hours trying to debug all the errors I got when running LDetect, but unfortunately cannot debug an error you are getting but I did not. 

My strategy was to read the error, and then go inspect that part of the code in LDetect to see what it is doing, and then try to figure out what the problem was. It's no fun, but if you really want the LD blocks I think you will have to do the same as I did.
