### ISSUE TITLE
Queries over LDblacks_GRCh38

### ISSUE THREAD

**Issue by jinghuazhao** [jmacdon/LDblocks_GRCh38#7]
Dear James,

I just came to your repository today which I believe to be very useful.  Can I have two queris:

1. Those at the data/ directory are ready to use for GRCh38 (should be straightforward to check but your comments will be great)?
2. We don't ever have  chromosome X definitions for hg19/hg38; is it possible to generate them or do I missing something?

I did make an attempt to liftover the original Ldect-data, https://bitbucket.org/nygcresearch/ldetect-data/src/master/, as noted here, https://github.com/jinghuazhao/pQTLtools/tree/master/inst/turboman, for Mahanttan plot as in https://jinghuazhao.github.io/tests/, but have always felt I may missed something and might as well simply refer to yours. 

Your comments are greatly appreciated,

Jing Hua

**Comment by jmacdon** [comment]
1.) Yes. 
2.) Neither pyrho nor deCode have recombination maps for chrX, so it's not possible to generate LD blocks

Using liftOver for LD blocks doesn't really work well. The original ldetect blocks are large enough that they tend to be split into smaller blocks and placed in non-contiguous positions in GRCh38. These positions can be quite distant, and even on other chromosomes. It doesn't make sense to think that a bunch of discontinuous blocks are still in LD, given the mechanism that causes LD in the first place, which is why we generated new blocks.
